### ISSUE TITLE
Any progress on this?

### ISSUE THREAD

**Issue by michaelkebe** [tonicsoft/slow-kotest#1]
I encountered the same problem and found this repo. Any workarounds or solutions yet?

I didn't know a better way to contact you...

**Comment by tonicsoft** [comment]
https://github.com/kotest/kotest/issues/2765 is now resolved. So, there is a workaround when using the command line to run tests.

However, the workaround doesn't work when running tests from the IDE. I have raised https://github.com/kotest/kotest/issues/3125 to report this.

Even though the classpath scanning issue is fixed, Kotest remains quite slow though. I have raised that issue here https://github.com/kotest/kotest/issues/3126

**Comment by tonicsoft** [comment]
@michaelkebe see response from kotest team on the issues above, everything can now be fixed by following the guidance on those tickets and using kotest 5.4.
